tyou_gridscale/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :login

  resources :users

  get '/ajax_login_regist_email_check', to: 'login#regist_email_check'

end

tyou_gridscale/app/models/user.rb
class User < ActiveRecord::Base

  # Validate User TABLE #
  validates :user_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :user_email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },uniqueness: true

  before_save { self.user_email = user_email.downcase }

  has_secure_password excetp:[:controller => 'login_controller', :action => 'create']


end

tyou_gridscale/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

  # catch 404 route error
  rescue_from ActionController::RoutingError, with: :render_404

  # catch 500 Internal Server Error (except Invalid Authenticity Token)
  rescue_from Exception, with: :render_500 unless Rails.env.development?

  # catch Invalid Authenticity Token (500 Internal Server Error)
  rescue_from ActionController::InvalidAuthenticityToken, with: :render_408

  def render_401
    flash.now[:danger] = 'Login'
    render :file => "#{Rails.root}/app/views/login/new.html.erb" , status: 401
  end

  # 404 page redirect
  def render_404
    render :file => "#{Rails.root}/app/views/errors/404.html.erb" , status: 404
  end

  def render_408
    flash.now[:danger] = 'controllers.login.login_in'
    render :file => "#{Rails.root}/app/views/login/new.html.erb" , status: 408
  end

  # 500 Internal Server Error
  def render_500
    flash.now[:danger] = get_message("main","main","main")
    render :file => "#{Rails.root}/app/views/main_menu/main.html.erb" , status: 500
  end

end

tyou_gridscale/app/controllers/login_controller.rb
class LoginController < ApplicationController

  def index

  end

  def new

    @user = User.new

  end

  def create

    begin

      @user = User.new(get_user_param)

      User.transaction do
        @user.save!
      end

      flash[:notice] = get_message("notice","101","Regist User Success")

      redirect_to controller: :users, action: :show

    rescue => e
      if e.message.present?
        throw_msg = e.message
        flash[:danger] = get_message("error","101",throw_msg)
      end
      # Create an error message.
      redirect_to controller: :login, action: :index
    # ensure
      # redirect_to controller: :login, action: :index, user_id: params[:para_uid]
    end

  end

  def update

    begin
      @user = User.find_by(user_key: param[:user_key])
      User.transaction do
        v.update_attributes!(user_email: "touree@me.com")
      end
    rescue => e
      if e.message.present?
        throw_msg = e.message
        flash[:danger] = get_message("error","101",throw_msg)
      end
      # Create an error message.

      redirect_to controller: :login, action: :index
    ensure
      redirect_to controller: :login, action: :edit, user_id: params[:user_key]
    end

  end

  def regist_email_check

    user_email = User.find_by(user_email: params[:user_email])

    msg_array = []
    if !user_email.blank?
      msg_array[0] = 0
      msg_array[1] = "メールアドレスはとうろくしました。"
    end

    respond_to do |format|
      format.html
      format.json {render json: msg_array}
    end

  rescue => e

    logger.error "regist_email_check: ==> " + e.to_s

  end


  private
  def get_user_param
    #params.require(:user).permit(:user_key, :user_name, :user_password)
    #params.require(:user).permit(:user_key, :user_name, :user_password).merge(updated_id: session[:user_name])
    params.require(:user).permit(:user_key, :user_email, :user_name, :user_password, :password, :password_confirmation)#.merge(password: params[:user_password], password_confirmation: params[:user_password])
  end

end

tyou_gridscale/app/controllers/users_controller.rb
class LoginController < ApplicationController


  def show

    @user = User.find(params[:id])

  end

  def edit



  end

  def update

    begin
      @user = User.find_by(user_key: param[:user_key])

      User.transaction do
        v.update_attributes!(user_email: "touree@me.com")
      end

    rescue => e
      if e.message.present?
        throw_msg = e.message
        flash[:danger] = get_message("error","101",throw_msg)
      end
      # Create an error message.

      redirect_to controller: :login, action: :index
    ensure
      redirect_to controller: :login, action: :edit, user_id: params[:user_key]
    end

  end

  private
  def get_user_param
    #params.require(:user).permit(:user_key, :user_name, :user_password)
    #params.require(:user).permit(:user_key, :user_name, :user_password).merge(updated_id: session[:user_name])
    #params.require(:user).permit(:user_key, :user_email, :user_name, :user_password, :password_digest).merge(password: param[:user_password], password_confirmation: param[:user_password])
  end

end

tyou_gridscale/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end


end

tyou_gridscale/app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "GridScale 株式会社"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  # get message
  def get_message(message_type, screen_code, message_code)
    message = '[' + message_type + screen_code + message_code + ']' + t('err_messages.' + message_code)
    html_statement(message)
  end

  # generate message for views
  def html_statement(str)
    str.gsub(/\\n/, '<br />').html_safe
  end

end

tyou_gridscale/app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  # def gravatar_for(user, size: 80 )
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

tyou_gridscale/app/helpers/welcome_helper.rb
module WelcomeHelper
end

tyou_gridscale/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.gridscale.com">Gridscale Inc.</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "News", '#' %></li>
    </ul>
  </nav>
</footer>

tyou_gridscale/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "グリッドスケール　株式会社", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "会社概要",   root_path %></li>
        <li><%= link_to "サービス",   root_path %></li>
        <li><%= link_to "事業内容",   root_path %></li>
        <li><%= link_to "お客様声",   root_path %></li>
        <li><%= link_to "ログイン", login_index_path %></li>
      </ul>
    </nav>
  </div>
</header>

tyou_gridscale/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

tyou_gridscale/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application',
                             'data-turbolinks-track' => 'reload' %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= html_statement(message) %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <br />
  <br />
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

tyou_gridscale/app/views/login/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <% provide(:title, 'Login') %>
</head>

<body>
<div class="center jumbotron">

</div>
</body>
</html>

tyou_gridscale/app/views/login/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <% provide(:title, 'Regist User' ) %>
</head>

<body>
<% provide(:screen_code, Constants::REGIST_USER_SCREEN ) %>

<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <%= form_for(@user, :url => {:controller => :login, :action => :create}) do |f| %>

        <%= f.label :user_key, t('views.user.user_key'), class: 'red_font' %>
        <%= f.text_field :user_key, class: 'form-control', maxlength: 16 %>

        <%= f.label :user_email, t('views.user.user_email'), class: 'red_font' %>
        <%= f.text_field :user_email, class: 'form-control', maxlength: 16 %>
        <%= label :email_repeat, '', class: 'red_font', id: 'email_repeat' %>
        <br />
        <%= f.label :user_name, t('views.user.user_name'), class: 'red_font' %>
        <%= f.text_field :user_name, class: 'form-control', maxlength: 60 %>

        <%= f.label :user_password, t('views.user.user_password'), class: 'red_font' %>
        <%= f.password_field :user_password, class: 'form-control', maxlength: 16 %>

        <%= f.label :password, t('views.user.user_password'), class: 'red_font' %>
        <%= f.password_field :password, class: 'form-control', maxlength: 16 %>

        <%= f.label :password_confirmation, t('views.user.user_password'), class: 'red_font' %>
        <%= f.password_field :password_confirmation, class: 'form-control', maxlength: 16 %>

        <br />
        <%= f.submit t('views.user.register'), class: "btn btn-primary" %>

    <% end %>
  </div>
</div>
<div id="login_view_notice" class="hidden" title=<%= 'views.common.delete' %>>
  <p> <%=  'This email is already regiest!' %> </p>
</div>
</body>
</html>



<script type="text/javascript">

    $(document).ready(function(){
        var loginViewJS = new LoginViewJS();

        $('#user_user_email').change(function() {
            loginViewJS._ajax_checkemail();
        });

    });

    function LoginViewJS() {};

    LoginViewJS.prototype._ajax_checkemail = function() {

        $.ajax({
            type: "GET",
            url: "<%= ajax_login_regist_email_check_path %>",
            dataType: "json",
            data: {user_email: $('#user_user_email').val()},
            success: function(data) {
                if (data != null) {
                    var json = $.parseJSON(JSON.stringify(data));
                    if (json[0] == 0) {
                        $("#login_view_notice").removeClass("hidden");
                        $('#login_view_notice').dialog({
                            resizable: false,
                            height: "auto",
                            width: 400,
                            modal: true,
                            buttons: {
                                OK: function () {
                                    $(this).dialog("close");
                                }
                            }
                        });
                        $("#email_repeat").html(json[1]);
                    } else {
                        $("#email_repeat").val('');
                    }
                }
            },
            error: function () {
                alert("Ajax Error");
            }
        });
    };

</script>

tyou_gridscale/app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <% provide(:title, 'Regist User' ) %>
</head>

<body>
<% provide(:screen_code, Constants::REGIST_USER_SCREEN ) %>

<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <%= form_for(@user, :url => {:controller => :login, :action => :create}) do |f| %>

        <%= f.label :user_key, t('views.user.user_key'), class: 'red_font' %>
        <%= f.text_field :user_key, class: 'form-control', maxlength: 16 %>

        <%= f.label :user_email, t('views.user.user_email'), class: 'red_font' %>
        <%= f.password_field :user_email, class: 'form-control', maxlength: 16 %>

        <%= f.label :user_name, t('views.user.user_name'), class: 'red_font' %>
        <%= f.text_field :user_name, class: 'form-control', maxlength: 60 %>

        <%= f.label :user_password, t('views.user.user_password'), class: 'red_font' %>
        <%= f.password_field :user_password, class: 'form-control', maxlength: 16 %>
        <br />
        <%= f.submit t('views.user.register'), class: "btn btn-primary" %>

    <% end %>
  </div>
</div>
</body>
</html>



<script type="text/javascript">
    $(document).ready(function(){
        // put all javascript here

    });
</script>

tyou_gridscale/app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <% provide(:title, 'Regist User' ) %>
</head>

<body>
<% provide(:screen_code, Constants::REGIST_USER_SCREEN ) %>

<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <%= form_for(@user, :url => {:controller => :login, :action => :create}) do |f| %>

        <%= f.label :user_key, t('views.user.user_key'), class: 'red_font' %>
        <%= f.text_field :user_key, class: 'form-control', maxlength: 16 %>

        <%= f.label :user_email, t('views.user.user_email'), class: 'red_font' %>
        <%= f.password_field :user_email, class: 'form-control', maxlength: 16 %>

        <%= f.label :user_name, t('views.user.user_name'), class: 'red_font' %>
        <%= f.text_field :user_name, class: 'form-control', maxlength: 60 %>

        <%= f.label :user_password, t('views.user.user_password'), class: 'red_font' %>
        <%= f.password_field :user_password, class: 'form-control', maxlength: 16 %>
        <br />
        <%= f.submit t('views.user.register'), class: "btn btn-primary" %>

    <% end %>
  </div>
</div>
</body>
</html>



<script type="text/javascript">
    $(document).ready(function(){
        // put all javascript here

    });
</script>

tyou_gridscale/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

tyou_gridscale/app/views/welcome/index.html.erb
<div class="center jumbotron">
  <h1>WE ARE GRIDSCALE</h1>

  <h2>
    Take a better life,Make a better world! >>
    <a href="http://www.gridscal.com/">http://www.gridscal.com</a>
  </h2>

  <%= link_to "JION US NOW !", new_login_path, class: "btn btn-lg btn-primary" %>
</div>